package Mapeos;

import javax.persistence.*;
import java.io.Serializable;

/**
 * Empleado generated by hbm2java
 */
@Entity
@Table(name = "Empleado")
public class Empleado implements Serializable {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "noEmpleado")  // Clave primaria mapeada a la columna noEmpleado
    private Integer noEmpleado;

    @Column(name = "nombreEmpleado", nullable = false)  // nombreEmpleado es obligatorio
    private String nombreEmpleado;

    @Column(name = "password", nullable = false)  // password es obligatorio
    private String password;

    @Column(name = "apellPatEmpleado", nullable = false)  // apellPatEmpleado es obligatorio
    private String apellPatEmpleado;

    @Column(name = "apellMatEmpleado", nullable = false)  // apellMatEmpleado es obligatorio
    private String apellMatEmpleado;

    @Column(name = "fechaNac", nullable = false)  // fechaNac es obligatorio
    private String fechaNac;

    @Column(name = "rfce", nullable = false, unique = true)  // rfce es obligatorio y único
    private String rfce;

    @Column(name = "salario", nullable = false)  // salario es obligatorio
    private int salario;

    @Column(name = "estadoCivil", nullable = false)  // estadoCivil es obligatorio
    private String estadoCivil;

    @Column(name = "estatus", nullable = false)  // estatus es obligatorio
    private String estatus;

    @Column(name = "nivelEstudio", nullable = false)  // nivelEstudio es obligatorio
    private String nivelEstudio;

    @Column(name = "tipoUsuario", nullable = false)  // tipoUsuario es obligatorio
    private String tipoUsuario;

    public Empleado() {
    }

    public Empleado(String rfce, int salario) {
        this.rfce = rfce;
        this.salario = salario;
    }

    public Empleado(String nombreEmpleado, String password, String apellPatEmpleado, String apellMatEmpleado, String fechaNac, String rfce, int salario, String estadoCivil, String estatus, String nivelEstudio, String tipoUsuario) {
        this.nombreEmpleado = nombreEmpleado;
        this.password = password;
        this.apellPatEmpleado = apellPatEmpleado;
        this.apellMatEmpleado = apellMatEmpleado;
        this.fechaNac = fechaNac;
        this.rfce = rfce;
        this.salario = salario;
        this.estadoCivil = estadoCivil;
        this.estatus = estatus;
        this.nivelEstudio = nivelEstudio;
        this.tipoUsuario = tipoUsuario;
    }

    // Getters and Setters

    public Integer getNoEmpleado() {
        return noEmpleado;
    }

    public void setNoEmpleado(Integer noEmpleado) {
        this.noEmpleado = noEmpleado;
    }

    public String getNombreEmpleado() {
        return nombreEmpleado;
    }

    public void setNombreEmpleado(String nombreEmpleado) {
        this.nombreEmpleado = nombreEmpleado;
    }

    public String getPassword() {
        return password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    public String getApellPatEmpleado() {
        return apellPatEmpleado;
    }

    public void setApellPatEmpleado(String apellPatEmpleado) {
        this.apellPatEmpleado = apellPatEmpleado;
    }

    public String getApellMatEmpleado() {
        return apellMatEmpleado;
    }

    public void setApellMatEmpleado(String apellMatEmpleado) {
        this.apellMatEmpleado = apellMatEmpleado;
    }

    public String getFechaNac() {
        return fechaNac;
    }

    public void setFechaNac(String fechaNac) {
        this.fechaNac = fechaNac;
    }

    public String getRfce() {
        return rfce;
    }

    public void setRfce(String rfce) {
        this.rfce = rfce;
    }

    public int getSalario() {
        return salario;
    }

    public void setSalario(int salario) {
        this.salario = salario;
    }

    public String getEstadoCivil() {
        return estadoCivil;
    }

    public void setEstadoCivil(String estadoCivil) {
        this.estadoCivil = estadoCivil;
    }

    public String getEstatus() {
        return estatus;
    }

    public void setEstatus(String estatus) {
        this.estatus = estatus;
    }

    public String getNivelEstudio() {
        return nivelEstudio;
    }

    public void setNivelEstudio(String nivelEstudio) {
        this.nivelEstudio = nivelEstudio;
    }

    public String getTipoUsuario() {
        return tipoUsuario;
    }

    public void setTipoUsuario(String tipoUsuario) {
        this.tipoUsuario = tipoUsuario;
    }
}


