package Mapeos;

import javax.persistence.*;

/**
 * Estado generated by hbm2java
 */
@Entity
@Table(name="Estado")
public class Estado  implements java.io.Serializable {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name="idEstado")
    private Integer idEstado;

    @Column(name="nombreEstado")
    private String nombreEstado;

    public Estado() {
    }

    public Integer getIdEstado() {
        return this.idEstado;
    }

    public void setIdEstado(Integer idEstado) {
        this.idEstado = idEstado;
    }

    public String getNombreEstado() {
        return this.nombreEstado;
    }

    public void setNombreEstado(String nombreEstado) {
        this.nombreEstado = nombreEstado;
    }


}
